# Generated by Django 4.2 on 2024-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_alter_sprint_backlog_sprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epica',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='epica',
            name='fecha_inicio',
            field=models.DateField(blank=True),
        ),
    ]
